read in full model options from info folder of output zip
mrc-ide/naomi pull request #320
Opened 2022-05-27 14:55 UTC by rtesra

This PR changes the model options read in by `read_output_package` to ensure that all model options are returned

2022-09-23 14:18 UTC, rtesra commented
hintr build https://github.com/mrc-ide/hintr/pull/403

2022-09-23 14:34 UTC, r-ash requested changes
Nice one, this looks like a great way of rendering the README. Great test too. One small comment about the default value

2022-09-23 14:35 UTC, rtesra commented on inst/report/README.Rmd
> +  output_dir: "/var/folders/vk/s5m946h57g3dk4rm43k1zk2m0000gn/T//Rtmp2sXfWV/file2ae41bd72870"
Thanks forgot to change what when testing

2022-09-28 15:01 UTC, r-ash approved these changes

2022-09-28 15:01 UTC, merged