Add country to pjnz extract
mrc-ide/naomi pull request #338
Opened 2022-09-07 08:36 UTC by osymandius

Add country name to `extract_pjnz_one()`. Presently country name is not extracted when subnational Spectrum files are used.

2022-09-08 10:50 UTC, jeffeaton commented
Thanks very much. 

* Why do you want this?
* If extracting country name, please also extract the ISO3.
* Please add a test

2022-09-08 16:03 UTC, r-ash commented
hintr build https://github.com/mrc-ide/hintr/pull/402

2022-09-27 14:22 UTC, jeffeaton commented
> Thanks very much.
> 
> * Why do you want this?
> * If extracting country name, please also extract the ISO3.
> * Please add a test

I completed these tasks -- added `iso3` and added a test. I think it is ready to go now.

@osymandius @r-ash -- could you please review and merge?

Thanks,
Jeff

2022-09-28 11:09 UTC, r-ash requested changes
Small issue in hintr

2022-09-28 11:09 UTC, r-ash commented on R/inputs-spectrum.R
> -  }
The hintr test data https://github.com/mrc-ide/hintr/blob/master/tests/testthat/testdata/Malawi2019.PJNZ relied on this conditional to work

```
> read_spectrum_region_name("tests/testthat/testdata/Malawi2019.PJNZ")
[1] NA
> eppasm::read_country("tests/testthat/testdata/Malawi2019.PJNZ")
[1] "Malawi"
```

The NA is causing problems further downstream when trying to generate output. Is this an issue of old test data in hintr or can we still get countries where the spectrum region code is 0?

2022-09-28 14:59 UTC, r-ash approved these changes

2022-09-28 14:59 UTC, merged