Return more informative error if comparison data not avaialble
mrc-ide/naomi pull request #341
Opened 2022-09-16 16:00 UTC by r-ash

2022-09-17 14:39 UTC, jeffeaton requested changes
Thanks, looks good; just a couple of small requests.

I am on leave next week so please don't wait for me to review again to merge.

2022-09-17 14:39 UTC, jeffeaton commented on tests/testthat/test-hintr-plot-data.R
> +               "Model output out of date please re-run model and try again")
Can you please add punctuation on this error message?
```
"Model output out of date. Please re-run model and try again."
```

2022-09-17 14:39 UTC, jeffeaton commented on NEWS.md
> +* `hintr_comparison_plot` will error if comparison plot data does not exist.
Edit `hints_comparison_plot` -> `hintr_comparison_plot()` for clarity.

2022-09-20 09:53 UTC, r-ash commented
hintr PR https://github.com/mrc-ide/hintr/pull/406

2022-09-21 09:42 UTC, rtesra approved these changes

2022-09-21 10:34 UTC, merged