This branch tries to (and ultimately fails) speed up the review input…
mrc-ide/naomi pull request #440
Opened 2024-09-06 17:32 UTC by M-Kusumgar

…s metadata endpoint in Hintr. Profiling the code revealed these Naomi functions were the slow parts. After optimising these they are many times faster on the test data and the MWI data however where we ultimately fail is DRC for which there is only a slight speed up because the majority of the time for it is spent calculating the other plot types like art_new_total, art_new_adult_m, etc. We have a solution for this that will probably get done in a PR after the plot refactor. For now, the main changes in this PR:

* drop_geometry arg to aggregate functions to skip unnecessary work (these functions were trying to drop geometry after it had already been dropped so wasting a lot of time reading the files)
* small test fix, we should be checking `check3` (defined in the lines just above the diff) and not `check1`
* new algorithm for aggregating up data, it is just a for loop that works level by level to aggregate up the data
* same new algorithm is also applied to calculating `missing_map`

2024-09-10 09:44 UTC, r-ash commented
Hintr PR https://github.com/mrc-ide/hintr/pull/524

2024-09-10 09:57 UTC, r-ash requested changes
This looks good to me, and hintr tests are passing with this branch so looking good. I think you can ignore that devl branch failure for some reason it is running really slowly but I don't think raising any real issues.

Really need to sort out this duckdb install stuff, not sure why it is not working from binary. (Maybe we'll have to run these tests inside docker again if I can't get that install working)

2024-09-12 10:27 UTC, M-Kusumgar commented on R/input-time-series.R
> +aggregate_art <- function(art, shape, drop_geometry = TRUE) {
ah okay looking at it properly, we were passing in `shape` to this function not `areas` (`areas` is result of reading the file and geometry dropped) so i can remove this arg and pass in `areas` only

2024-09-12 11:21 UTC, M-Kusumgar commented on R/input-time-series.R
> +aggregate_art <- function(art, shape, drop_geometry = TRUE) {
just added a check for if its a table then no point reading it again

2024-09-13 14:24 UTC, r-ash approved these changes
This looks good to me. I'd like @rtesra to check the data manipulation before we merge but all fine from my end.

2024-10-02 14:45 UTC, merged