Add function to create datapack download standalone
mrc-ide/naomi pull request #460
Opened 2024-12-06 08:21 UTC by r-ash

2024-12-06 12:42 UTC, rtesra approved these changes

2024-12-06 13:03 UTC, jeffeaton requested changes
Per discussion: Make this an Excel download workbook with the data pack CSV on the first sheet, and the metadata discussed on second sheet. (Feel free to split up to more sheets if useful)

What is the filename for the download? Is that specified here or in hintr?

2024-12-06 21:11 UTC, r-ash commented
> What is the filename for the download? Is that specified here or in hintr?

That is in hintr. I did mean to ask about that actually but then slipped my mind. At the moment it will be `$iso3_datapack_$date.xlsx` which fits the general structure of the other files. But let me know if you'd like anything else.

2024-12-08 20:39 UTC, jeffeaton commented
> > What is the filename for the download? Is that specified here or in hintr?
> 
> That is in hintr. I did mean to ask about that actually but then slipped my mind. At the moment it will be `$iso3_datapack_$date.xlsx` which fits the general structure of the other files. But let me know if you'd like anything else.

Can we do: `$iso3_pepfar-tst-2025_$date-time.xlsx`?

Analogous to we do for main output: `BWA_naomi-output_20241208-2036.zip`

Let's connect tomorrow and see if we can pin down that metadata sheet?

2024-12-10 18:59 UTC, merged